### ISSUE TITLE
Guohe Q900: Connecting enables PTT and "hangs"

### ISSUE THREAD

**Issue by akira25** [Hamlib/Hamlib#1901]
**Describe the bug**
When connecting via HAMLIB to the Q900, PTT gets enabled and "hangs" until released forcefully. This can either happen by pressing the [PTT] key at the device, or by directly sending `T 0` command.

The `T 0` command takes some seconds, to return successful

**To Reproduce**
Steps to reproduce the behavior (please use `rigctl` with the `-vvvvv` option if at all possible and post the output under number 4 below):
1. `rigctl` model: 1051
2. The function that fails, i.e. `rig_open`, `rig_set_freq`, `rig_get_freq`, etc.: I don't know.
3. Hamlib version: 4.6.4
4. Post `rigctl` output:

```
rigctl.c(532) Startup: rigctl -m 1051 -r /dev/serial/by-id/usb-GHDZ_Community_USB_Q900_00000000002A-if00 -vvvv
rigctl Hamlib 4.6.4 2025-07-18T18:23:23Z SHA=59e3d1 64-bit
Report bugs to <hamlib-developer@lists.sourceforge.net>

rig_init: 2038 time test passed
yaesu: initrigs4_yaesu called
rig_init: rig_model=Guohe Q900 20241117.0
rig_init: rig has VFO_A
rig_init: rig has VFO_B
ft817_init: called, version 20241117.0
rig_set_conf called
rig_confparam_lookup called for rig_pathname
rig_set_conf: rig_pathname='/dev/serial/by-id/usb-GHDZ_Community_USB_Q900_00000000002A-if00'
rig.c(970):rig_open entered
serial_open: /dev/serial/by-id/usb-GHDZ_Community_USB_Q900_00000000002A-if00
rig_open: 0x55e964c34e64 rs->comm_state==1?=1
ft817_open: called 
*1:rig.c(3463):rig_get_vfo entered
rig_lock: client lock engaged
ft817_get_vfo: called 
ft817_read_eeprom: called
read_block_generic called, direct=1
ft817_read_eeprom: data[0]=81, data[1]=00, out=81
*1:rig_get_vfo: elapsed=5ms
rig_lock: client lock disengaged
*1:rig.c(3534):rig_get_vfo returning(0) 
*1:rig.c(8424):async_data_handler_start entered
*1:rig.c(8431):async_data_handler_start returning(0) 
*1:rig.c(2452):rig_get_freq entered
rig_get_freq called vfo=VFOA
rig_get_freq(2470) called vfo=VFOA
rig.c(2479) vfo=VFOA, curr_vfo=VFOB
rig_lock: client lock engaged
rig_get_freq(2585): vfo_opt=0, model=1051
ft817_get_freq: called, vfo=VFOA, ptt=0, split=0
ft817_get_status: called
read_block_generic called, direct=1
from_bcd_be called
ft817_set_vfo: called vfo=VFOA
ft817_get_vfo: called 
ft817_read_eeprom: called
read_block_generic called, direct=1
ft817_read_eeprom: data[0]=81, data[1]=00, out=81
ft817_send_cmd: called
ft817_read_ack: called
read_block_generic called, direct=1
ft817_get_freq: called, vfo=VFOA, ptt=0, split=0
ft817_get_status: called
read_block_generic called, direct=1
from_bcd_be called
ft817_set_vfo: called vfo=VFOB
ft817_get_vfo: called 
ft817_read_eeprom: called
read_block_generic called, direct=1
ft817_read_eeprom: data[0]=80, data[1]=00, out=80
ft817_send_cmd: called
ft817_read_ack: called
read_block_generic called, direct=1
*1:rig_get_freq: elapsed=239ms
rig_lock: client lock disengaged
*1:rig.c(2722):rig_get_freq returning(0) 
*1:network.c(1589):network_multicast_publisher_start entered
network.c(1598): multicast publisher address=0.0.0.0, port=4532
*1:network.c(1618):network_multicast_publisher_start returning(0) 
*1:network.c(1800):network_multicast_receiver_start entered
network.c(1810): multicast receiver address=0.0.0.0, port=4532
*1:network.c(1819):network_multicast_receiver_start returning(0) 
*1:event.c(272):rig_poll_routine_start entered
*1:event.c(312):rig_poll_routine_start returning(0) 
rig.c(303):add_opened_rig entered
rig.c(315):add_opened_rig returning2(0) 
rig.c(1656):rig_open returning2(0) 
Opened rig model 1051, 'Q900'
Backend version: 20241117.0, Status: Stable

Rig command: event.c(85): Starting rig poll routine thread
```

**Expected behavior**
Instead of engaging the PTT directly on cennecting to the Q900, Id would be great, to disengage/leave it.

**Desktop (please complete the following information):**
 - OS: Fedora 42, x86_64 Desktop
 - Client application: rigctl directly, also happens with WSJT-X and other programs
 - Client application version: Hamlib 4.6.4

**Comment by akira25** [comment]
This issue still persists with the most recent main-branch:

```
./usr/local/bin/rigctl -m 40002 -r /dev/serial/by-id/usb-GHDZ_Community_USB_Q900_00000000002A-if00 -vvvv 'f'
rigctl.c(471) Startup: ./usr/local/bin/rigctl -m 40002 -r /dev/serial/by-id/usb-GHDZ_Community_USB_Q900_00000000002A-if00 -vvvv f
rigctl Hamlib 4.7~git 2025-09-08T00:33:37Z SHA=a93132 64-bit
Report bugs to <hamlib-developer@lists.sourceforge.net>

rig_init: 2038 time test passed
initrigs4_guohetec: Initializing guohetec 
initrigs4_guohetec: Loading guohetec backend
rig_init: rig_model=GUOHETEC Q900 20250611.0
rig_init: rig has VFO_A
rig_init: rig has VFO_B
q900_init: called, version 20250611.0
rig_set_conf called
rig_confparam_lookup called for rig_pathname
rig_set_conf: rig_pathname='/dev/serial/by-id/usb-GHDZ_Community_USB_Q900_00000000002A-if00'
rig.c(1051):rig_open entered
serial_open: /dev/serial/by-id/usb-GHDZ_Community_USB_Q900_00000000002A-if00
rig_open: 0x18305e64 rs->comm_state==1?=1
q900_open: called 
*1:rig.c(3529):rig_get_vfo entered
rig_lock: client lock engaged
q900_send_cmd1: called
read_block_generic called, direct=1
read_block_generic(): Timed out 0.410516 seconds after 0 chars, direct=1
q900_get_vfo: Failed to read header, using cached values
*1:rig_get_vfo: elapsed=411ms
rig_lock: client lock disengaged
*1:rig.c(3600):rig_get_vfo returning(0) 
*1:rig.c(8485):async_data_handler_start entered
*1:rig.c(8492):async_data_handler_start returning(0) 
*1:rig.c(2518):rig_get_freq entered
rig_get_freq called vfo=VFOA
rig_get_freq(2536) called vfo=VFOA
rig.c(2545) vfo=VFOA, curr_vfo=None
rig_lock: client lock engaged
rig_get_freq(2651): vfo_opt=0, model=40002
read_block_generic called, direct=1
read_block_generic(): Timed out 0.411781 seconds after 32 chars, direct=1
read_block_generic called, direct=1
read_block_generic(): Timed out 0.410809 seconds after 32 chars, direct=1
read_block_generic called, direct=1
read_block_generic(): Timed out 0.410902 seconds after 32 chars, direct=1
read_block_generic called, direct=1
read_block_generic(): Timed out 0.410994 seconds after 32 chars, direct=1
read_block_generic called, direct=1
read_block_generic(): Timed out 0.410961 seconds after 32 chars, direct=1
q900_get_freq: Successfully got VFOA=29501600 Hz, VFOB=28074000 Hz
*1:rig_get_freq: elapsed=2157ms
rig_lock: client lock disengaged
*1:rig.c(2788):rig_get_freq returning(0) 
*1:network.c(1587):network_multicast_publisher_start entered
network.c(1596): multicast publisher address=0.0.0.0, port=4532
*1:network.c(1616):network_multicast_publisher_start returning(0) 
*1:network.c(1798):network_multicast_receiver_start entered
network.c(1808): multicast receiver address=0.0.0.0, port=4532
*1:network.c(1817):network_multicast_receiver_start returning(0) 
*1:event.c(269):rig_poll_routine_start entered
*1:event.c(309):rig_poll_routine_start returning(0) 
rig.c(329):add_opened_rig entered
rig.c(341):add_opened_rig returning2(0) 
rig.c(1730):rig_open returning2(0) 
Opened rig model 40002, 'Q900'
event.c(82): Starting rig poll routine thread
Backend version: 20250611.0, Status: Stable
rigctl_parse.c(2204):rigctl_get_freq entered
*1:rig.c(2518):rig_get_freq entered
rig_get_freq called vfo=currVFO
rig_get_freq(2536) called vfo=currVFO
rig.c(2545) vfo=currVFO, curr_vfo=None
rig_lock: client lock engaged
*1:rig_get_freq: elapsed=0ms
rig_lock: client lock disengaged
*1:rig.c(2631):rig_get_freq returning(0) 
29501600
rigctl_parse.c(2230):rigctl_get_freq returning2(0) 
*1:rig.c(1759):rig_close entered
**2:rig.c(8605):morse_data_handler_stop entered
**2:rig.c(8651):morse_data_handler_stop returning(0) 
**2:rig.c(8566):async_data_handler_stop entered
**2:rig.c(8597):async_data_handler_stop returning(0) 
**2:event.c(324):rig_poll_routine_stop entered
event.c(250): Stopping rig poll routine thread
**2:event.c(359):rig_poll_routine_stop returning(0) 
**2:network.c(1906):network_multicast_receiver_stop entered
**2:network.c(1915):network_multicast_receiver_stop returning(0) 
**2:network.c(1738):network_multicast_publisher_stop entered
**2:network.c(1747):network_multicast_publisher_stop returning(0) 
q900_close: called 
ser_close: restoring options
rig_close(1900): 0x18305e64 rs->comm_state==0?=0
*1:rig.c(1904):rig_close returning(0) 
q900_cleanup: called

```

After disconnecting from the rigctl, the PTT is released by itself, though.

**Comment by N0NB** [comment]
Thanks for testing the model in the `master` branch.

@FVsonar Can you help with this?

**Comment by N0NB** [comment]
So far nothing heard from @FVsonar who worked on this code most recently.

**Comment by FVsonar** [comment]
Hi,

Thank you for reporting this issue.

This specific problem with the Q900/PMR171 (PTT being unexpectedly activated on connect) has already been addressed in the latest development code. 
To resolve this issue, please compile Hamlib from the latest source code on the main (or master) branch. The fix is not yet included in any stable release (like 4.6.4), so installing from your distribution's package manager will not help.

Here are the steps to compile from source:


# Clone the latest Hamlib source
git clone https://github.com/Hamlib/Hamlib.git
cd Hamlib

# Bootstrap (if building from git)
./bootstrap

# Configure, compile and install
./configure
make
sudo make install

# You may need to update your library cache
sudo ldconfig
After compiling and installing the latest source, the PTT should no longer be activated when connecting to your Q900.

Please let us know if you still experience the issue after building from the latest source. We can then investigate further.

**Comment by N0NB** [comment]
For whatever reason, @FVsonar's message does not appear in issue #1901.

@FVsonar, @akira25 shows in message
https://github.com/Hamlib/Hamlib/issues/1901#issuecomment-3271629808
that the issue persists in 4.7~git.  Please look at the message through
the GitHub Web interface and reply there.

73, Nate

(click the dots to see @FVsonar's message)

----- Forwarded message from FVsonar ***@***.***> -----

Date: Tue, 07 Oct 2025 23:23:12 -0700

**Comment by akira25** [comment]
Tested that one moment ago with 23710cf2da3d8a05c7ed0b9bdecefe020404f0d1 from the main branch. Unfortunately, the issue still persist.

Do you have the mentioned patch at hand (its commit-id)? I might have a look myself too.

Since the radio works great, after init and disengaging the hanging PTT, I assume an init-error. I have tested to disengage the PTT directly at the end of the assumed init-code, which worked great as a workaround, but still triggers a short engagement of PTT.

**Comment by N0NB** [comment]
Here is the commit history:  https://github.com/Hamlib/Hamlib/commits/master/rigs/guohetec/q900.c

**Comment by FVsonar** [comment]
I've consulted with the product development team, and the issue appears to stem from RTS/DTR control. They have acknowledged it and plan to fix it in a future update. In the meantime, perhaps you could try manually setting RTS/DTR before initialization?

**Comment by akira25** [comment]
@FVsonar Are there any updates on this issue? :)

**Comment by FVsonar** [comment]
@akira25 
After investigation, I've confirmed the root cause:

Root cause: The Linux kernel raises the DTR pin by default when open() is called on a serial port (POSIX standard behavior). On the Q900, the DTR pin is wired to the PTT control circuit. So when the serial port is opened, DTR goes high, immediately putting the radio into transmit mode. The PTT gets "stuck" because the DTR level stays high.

Fix: I'll add explicit ioctl(TIOCMBIC) calls in q900_open() and pmr171_open() to clear the DTR line, preventing the kernel's default behavior from triggering unwanted PTT.

I'll submit the fix when I have time. Thanks for opening this issue.

**Comment by akira25** [comment]
@FVsonar Is the suggested fix submitted already? Would love to try out some neat ft8 on Q900. :)
